### ISSUE TITLE
Black Screen when entering in GameMode on Mac M2

### ISSUE THREAD

**Issue by DavidGiraldoCode** [GarrettGunnell/CS2-Smoke-Grenades#1]
Hello GOAT,

I cloned the repo and installed the corresponding Unity version, but once I hit play, it all went black.
I am using a MacBook Pro M2, I am using version **2021.3.15f1 Silicon LTS**. I haven't tested it on a Windows yet.

Any ideas? I would appreciate any insight you can give me. Thanks for all the fantastic work you share on YT.

Best,
David

 The only alert I have on the console is:
 
 ```bash
Shader warning in 'Voxelize': use of potentially uninitialized variable (IntersectsTriangleAabb) at kernel CS_VoxelizeMesh at Voxelize.compute(102) (on metal)
```
This is what I see:
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/de3ec903-9bfe-4464-84fd-b1345685b054">

**Comment by GarrettGunnell** [comment]
I develop on windows sorry. With how mac is, you can assume nothing works on it.
